# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: Build with Gradle
#      run: ./gradlew build
    - name: Install Infer
      run: |
        VERSION=1.0.0
        curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v$VERSION.tar.xz" | sudo tar -C /opt -xJ 
        sudo ln -s "/opt/infer-linux64-v$VERSION/bin/infer" /usr/local/bin/infer
#        ls "/opt/infer-linux64-v$VERSION/bin"
#        ls /usr/local/bin
# Install the latest version. (Install it into ./bin/ by default).
    - name: Install Reviewdog
      uses: reviewdog/action-setup@v1
    - name: Print Reviewdog version
      run: reviewdog -version
#      run: |
#        curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
#        ls ./bin
    - name: Run Infer
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./gradlew clean
        echo "*** Starting raw infer ***"
        infer run -- ./gradlew build
        echo "*** Ending raw infer ***"
        ./gradlew clean
        echo "*** Starting reveiwdog infer ***"
        infer run -- ./gradlew build | reviewdog -efm="%f:%l: %m" -name="infer" -reporter=github-pr-check
        echo "*** Ending raw infer ***"
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-gradle
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-gradle
# https://github.com/spring-io/sagan/wiki/Run-the-site-on-Cloud-Foundry
    - name: Build Artifacts
      run: |
        cd sagan-site
        ../gradlew build -x check
        ls build/libs
    - name: Save Artifacts/Packages
      uses: actions/upload-artifact@v2
      with:
        name: sagan-site-1.0.0-SNAPSHOT.jar
        path: sagan-site/build/libs

