# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: Build with Gradle
#      run: ./gradlew build
    - name: Install Infer
      run: |
        VERSION=1.0.0
        curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v$VERSION.tar.xz" | sudo tar -C /opt -xJ 
        sudo ln -s "/opt/infer-linux64-v$VERSION/bin/infer" /usr/local/bin/infer
#        ls "/opt/infer-linux64-v$VERSION/bin"
#        ls /usr/local/bin
# Install the latest version. (Install it into ./bin/ by default).
    - name: Install Reviewdog
      run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
      # https://github.com/spring-io/sagan/wiki/Run-the-site-on-Cloud-Foundry
    - name: Run Infer
      run: |
        cd sagan-site
        infer run -- ./gradlew clean build -x check
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-gradle
    - name: Save Artifacts/Packages
      uses: actions/upload-artifact@v2
      with:
        name: sagan-site
        path: build/libs

